# Generated by Django 5.1.6 on 2025-02-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
